name: Terraform Prod Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'environments/prod/**'
      - 'modules/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: environments/prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false -var "prod_access_key=${{ secrets.AWS_ACCESS_KEY_ID_PROD }}" -var "prod_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}"

      - name: Terraform Apply
        run: terraform apply -input=false tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
